apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.env.APP_DEBUG | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_DATABASE: {{ .Values.db.name | quote }}
  DB_USERNAME: {{ .Values.db.user | quote }}
